options:
  influx_host:
    type: string
    default: ""
    description: Hostname for InfluxDB, will be replaced if you add an influxdb relation
  influx_port:
    type: string
    default: "8086"
    description: Port for InfluxDB, will be replaced if you add an influxdb relation
  influx_user:
    type: string
    default: root
    description: user for InfluxDB, will be replaced if you add an influxdb relation
  influx_password:
    type: string
    default: root
    description: password for InfluxDB, will be replaced if you add an influxdb relation
