#!/usr/bin/python

import os
import os.path
import shutil

import setup

setup.pre_install()

from charmhelpers.core import hookenv
from charmhelpers.core.hookenv import service_name, log
from charmhelpers.core.templating import render
from charmhelpers.core.host import mkdir


def setup_upstart_jobs():
    hookenv.log('setting up upstart job')
    working_dir = os.getcwd()
    charm_upstart_conf = "/var/lib/charm/{}/upstart.conf".format(
        service_name())
    mkdir(os.path.dirname(charm_upstart_conf))
    context = {'decoder_path': '{}/hooks/admin_ceph'.format(working_dir),
               'decoder_options': '/etc/default/decode_ceph.yaml',
               'name': 'decode_ceph'}

    render('upstart.conf', charm_upstart_conf, context, perms=0o644)
    log('copying {} to /etc/init/admin_ceph.conf'.format(charm_upstart_conf))
    shutil.copy(charm_upstart_conf, '/etc/init/decode_ceph.conf')


def install():
    hookenv.log('Installing ceph-metrics-collector')
    setup_upstart_jobs()


if __name__ == "__main__":
    install()
