#!/usr/bin/python

import setup

setup.pre_install()

from charmhelpers import fetch
from charmhelpers.core import hookenv


def install():
    hookenv.log('Installing ceph-metrics-collector')
    fetch.add_source(source='deb http://packages.elasticsearch.org/logstash/1.5/debian stable main',
                     key='D88E42B4')
    fetch.apt_update()
    fetch.apt_install(fetch.filter_installed_packages(['collectd', 'collectd-utils', 'logstash', 'libpcap-dev']))


if __name__ == "__main__":
    install()
